#include "ATA_PIO_LBA28.h"
#include "serial.h"

// See https://wiki.osdev.org/ATA_PIO_Mode#Registers
#define PRIMARY_IO_0 0x1F0
#define PRIMARY_IO_1 PRIMARY_IO_0 + 1
#define PRIMARY_IO_2 PRIMARY_IO_0 + 2
#define PRIMARY_IO_3 PRIMARY_IO_0 + 3
#define PRIMARY_IO_4 PRIMARY_IO_0 + 4
#define PRIMARY_IO_5 PRIMARY_IO_0 + 5
#define PRIMARY_IO_6 PRIMARY_IO_0 + 6
#define PRIMARY_IO_7 PRIMARY_IO_0 + 7
#define PRIMARY_CMD_0 = 0x3F6
#define PRIMARY_CMD_1 = PRIMARY_CMD_0 + 1

#define SECONDARY_IO_0 0x170
#define SECONDARY_IO_1 SECONDARY_IO_0 + 1
#define SECONDARY_IO_2 SECONDARY_IO_0 + 2
#define SECONDARY_IO_3 SECONDARY_IO_0 + 3
#define SECONDARY_IO_4 SECONDARY_IO_0 + 4
#define SECONDARY_IO_5 SECONDARY_IO_0 + 5
#define SECONDARY_IO_6 SECONDARY_IO_0 + 6
#define SECONDARY_IO_7 SECONDARY_IO_0 + 7
#define SECONDARY_CMD_0 = 0x376
#define SECONDARY_CMD_1 = SECONDARY_CMD_0 + 1

uint8 get_status()
{
    return inb(PRIMARY_IO_7);
}